CREATE TABLE IF NOT EXISTS task_view (
    task_id VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    assigned_group VARCHAR(255) NOT NULL,
    assigned_user VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    deadline TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_trail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(255) NOT NULL,
    event_timestamp TIMESTAMP NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload VARCHAR(4000),
    recorded_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_task_id ON audit_trail(task_id);
